/* eslint-disable @next/next/no-page-custom-font */
import React from "react";

export const metadata = {
  title: "Coding Adda - About Us",
  description: "Generated by Aditya Pandey",
};

const RootLayout = ({ children }) => {
  return (
    <>
      <>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik+Scribble&display=swap"
          rel="stylesheet"
        />
      </>
      <div>{children}</div>
    </>
  );
};

export default RootLayout;
