import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
// import { connect } from "mongoose";
import mongoose from "mongoose";
import "react-toastify/dist/ReactToastify.css";
import Toast from "@/components/Toast";
import UserWrapper from "@/context/UserWrapper";
import Footer from "@/components/Footer";
const uri = process.env.MONGO_URI;

// import Head from "next/head";
// import DarkMode from "@/components/DarkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coding Adda",
  description: "Generated by Aditya Pandey",
};

export default function RootLayout({ children }) {
  const connect = async () => {
    await mongoose.connect(uri);
    console.log("Connected to mongoos");
  };
  connect();
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/Main Logo.svg"
          sizes="any"
        />
      </head>
      <body className={inter.className}>
        <UserWrapper>
          <Header />
          <Toast />
          <div className="w-[90%] mx-auto md:pt-32 py-8 overscroll-x-contain overflow-x-auto">
            {children}
            <Footer />
          </div>
        </UserWrapper>
      </body>
    </html>
  );
}
