import React from 'react'

export const metadata = {
    title: "Coding Adda - Our Blogs",
    description: "Generated by Aditya Pandey",
  };

const RootLayout = ({children}) => {
  return (
    <div>
      {children}
    </div>
  )
}

export default RootLayout
